source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MCPagingIntroViewController_Example', :exclusive => true do
  pod 'MCPagingIntroViewController', :path => '../'
end

target 'MCPagingIntroViewController_Tests', :exclusive => true do
  pod 'MCPagingIntroViewController', :path => '../'

  
end
